### ISSUE TITLE
程序下载时提示MemoryError

### ISSUE THREAD

**Issue by easesoft** [brandonxiang/pyMap#2]
下载大级别时程序提示如下错误：
Traceback (most recent call last):
  File "pyMap.py", line 181, in <module>
    config()
  File "pyMap.py", line 166, in config
    process_latlng(top,left,bottom,right,zoom,name,maptype)
  File "pyMap.py", line 52, in process_latlng
    process_tilenum(left, right, top, bottom, zoom, output, maptype)
  File "pyMap.py", line 78, in process_tilenum
    _mosaic(left, right, top, bottom, zoom, output, filename)
  File "pyMap.py", line 109, in _mosaic
    output_im = Image.new("RGBA", (size_x, size_y))
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\PIL\Image.py", line 2036, in new
    return Image()._new(core.fill(mode, size, color))
MemoryError

**Comment by brandonxiang** [comment]
你下图范围太大了，你可以先试一下小范围。Python本身就极其消耗内存。或者换个电脑

**Comment by brandonxiang** [comment]
我曾经拼接过2g的png图片，结果烂电脑打不开图片。我觉得再大的图片可能也是打不开吧，除非硬件更好。
